export const _setRepSelection_              = '_setRepSelection_'
export const _setWeightSelection_           = '_setWeightSelection_'
export const _setNumberOfSets_              = '_setNumberOfSets_'
export const _setRange_                     = '_setRange_'
export const _setIndividualRep_             = '_setIndividualRep_'
export const _initiateWeightedArray_        = '_initiateWeightedArray_'
export const _initiateWeightlessArray_      = '_initiateWeightlessArray_'
