export * from './forms/Login'
export * from './forms/Signup'
export * from './lock/Unsecure'
export * from './lock/Secure'
export * from './menu/Menu'
export * from './nav/Nav'
export * from './opSwitch/OpSwitch'
//export * from './routing/PrivateRoute'
